"""High-watermark state for incremental Kalshi ingest.

Stored as JSON at `data/kalshi/_state.json`. Structure:

    {
      "trades_by_ticker": {
        "KXBTC-25JAN0117-B84500": {
          "last_trade_id": "...",
          "last_trade_time": "2025-01-01T10:30:45.123Z",
          "last_pulled_at": "2026-04-22T12:00:00Z"
        },
        ...
      },
      "events_last_pulled_at": {
        "KXBTC": "2026-04-22T12:00:00Z",
        "FED": "2026-04-22T12:00:00Z"
      }
    }

Separate from the parquet data so it can be regenerated by replaying the
parquets if needed.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

STATE_FILENAME = "_state.json"


def _state_path(root: Path) -> Path:
    return root / STATE_FILENAME


def load(root: Path) -> dict:
    p = _state_path(root)
    if not p.exists():
        return {"trades_by_ticker": {}, "events_last_pulled_at": {}}
    with open(p) as f:
        return json.load(f)


def save(root: Path, state: dict) -> None:
    p = _state_path(root)
    p.parent.mkdir(parents=True, exist_ok=True)
    tmp = p.with_suffix(p.suffix + ".tmp")
    with open(tmp, "w") as f:
        json.dump(state, f, indent=2, default=str)
    tmp.replace(p)


def last_trade_time(state: dict, ticker: str) -> datetime | None:
    entry = state.get("trades_by_ticker", {}).get(ticker)
    if not entry or not entry.get("last_trade_time"):
        return None
    raw = entry["last_trade_time"]
    if raw.endswith("Z"):
        raw = raw[:-1] + "+00:00"
    return datetime.fromisoformat(raw)


def update_trades(
    state: dict,
    ticker: str,
    last_trade_id: str | None,
    last_trade_time: datetime | None,
    pulled_at: datetime,
) -> None:
    if pulled_at.tzinfo is None:
        pulled_at = pulled_at.replace(tzinfo=timezone.utc)
    tbt = state.setdefault("trades_by_ticker", {})
    tbt[ticker] = {
        "last_trade_id": last_trade_id,
        "last_trade_time": (
            last_trade_time.isoformat() if last_trade_time else None
        ),
        "last_pulled_at": pulled_at.isoformat(),
    }


def update_events_pulled(
    state: dict, series_ticker: str, pulled_at: datetime
) -> None:
    if pulled_at.tzinfo is None:
        pulled_at = pulled_at.replace(tzinfo=timezone.utc)
    state.setdefault("events_last_pulled_at", {})[series_ticker] = (
        pulled_at.isoformat()
    )
